language: android
android:
 components:
  - tools
  - build-tools-23.0.2
  - android-23
  - extra-android-m2repository

  - sys-img-armeabi-v7a-android-21

script:
  # By default Travis-ci executes './gradlew build connectedCheck' if no 'script:' section found.
  - ./gradlew build